FROM node:18-alpine3.15

WORKDIR '/app'

COPY package.json .
RUN yarn install

# Can omit COPY in dev mode, since container has references to required files
# through volumes (for hot reloading of code changes).
# COPY . .

CMD ["yarn", "start"]